FROM eclipse-temurin:21-jdk AS builder
WORKDIR /workspace

COPY . .

ARG SERVICE_NAME
RUN chmod +x ./gradlew && ./gradlew :${SERVICE_NAME}:bootJar --no-daemon -x test

FROM eclipse-temurin:21-jre
WORKDIR /app

ARG SERVICE_NAME
COPY --from=builder /workspace/${SERVICE_NAME}/build/libs/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
