server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: vote-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/vote_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
    path: /swagger

app:
  kafka:
    vote-created-topic: vote-created

management:
  endpoints:
    web:
      exposure:
        include: health,info
